### ISSUE TITLE
Todo - Missing hydraulic system's features

### ISSUE THREAD

**Issue by vezza** [legoboyvdlp/A320-family#29]
hydraulic system missing features:
Done:

In progress:

To-do:
* [x] when you set parking brakes the pressure indicator on the flight deck should indicate the brakes pressure;
* [x] when both green and yellow hydraulic systems are INOP, brakes should rely on yellow accumulator pressure, if accumulator pressure is = 0 brakes shouldn't work;
* [x] Bug - Brakes are working even if hydraulic pressure is missing;
* [X] Green HYD resvoir rises on gear extension and falls at retraction, [source](https://www.youtube.com/watch?v=o0hr_qjJ9Go)
**Describe the solution you'd like**
don't know exactly how to proceed, it seems that the relevant code is there anyway I'm unable to understand where L/R brakes are getting hydraulic input/source

**Comment by legoboyvdlp** [comment]
Yep :)

**Comment by legoboyvdlp** [comment]
Is this the brake system?

**Comment by vezza** [comment]
Yes, the indicators on the flightdeck do not works...

**Comment by vezza** [comment]
I have reviewed this issue and I must confess I misunderstood the brakes pressure indicator on the flightdeck... It work fine except in one case: when you set parking brakes it should indicate the brakes pressure as the parking brake is operated by the yellow hydraulic system. The indicator on the flight deck shows only the yellow hydraulic pressure when in ALTN BRK mode or when parking brake is set. I've changed the subject of the issue in order to point the developers to the right direction.

**Comment by legoboyvdlp** [comment]
Todo redo braking system totally

**Comment by legoboyvdlp** [comment]
Not done yet, but did the ground work for this tonight.

**Comment by legoboyvdlp** [comment]
Seems this is completE?

**Comment by merspieler** [comment]
Nope,  Green HYD resvoir rises on gear extension and falls at retraction, is still missing.
Or the ecam page doesn't show it?

**Comment by legoboyvdlp** [comment]
Complete ...?

**Comment by merspieler** [comment]
Haven't fully tested it, but looks complete to me.
